import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { InstantSearch } from 'react-instantsearch';
import { instantMeiliSearch } from '@meilisearch/instant-meilisearch';

import NavBar from "@/components/NavBar/NavBar";
import "@/styles/globals.css";

const { searchClient } = instantMeiliSearch(
  process.env.MEILI_HOST_NAME || 'http://localhost:7700',
  process.env.MEILI_API_KEY
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <InstantSearch indexName="products" searchClient={searchClient}>
        <NavBar />
        {children}
      </InstantSearch>
      </body>
    </html>
  );
}
